services:
  - type: web
    name: amazon-clone-project
    env: static
    branch: main
    buildCommand: npm ci --prefix Amazon && npm run build --prefix Amazon
    staticPublishPath: Amazon/dist
    region: oregon
