services:
  - type: web
    name: amazon-clone-project
    env: static
    branch: main
  buildCommand: npm ci --prefix Amazon && npm run build --prefix Amazon && rm -rf dist && mv Amazon/dist dist
  staticPublishPath: dist
    region: oregon
